### ISSUE TITLE
Could not create key in storage hierarchy 

### ISSUE THREAD

**Issue by wojciechozga** [stefanberger/libtpms#34] opened 2019-03-22 11:20 UTC
Hello again!

I have manually started the tpm (via TPMLIB_MainInit()), then I executed TPM_Startup command. I provisioned new EK certificate (TPM_CreatePrimary under TPM_RH_ENDORSEMENT, issue cert, TPM_NV_DefineSpace, TPM_NV_Write). Then, I started the VM, and inside it, I read the certificate from the NV. Everything works fine so far.

Then, I try to create new attestation key. The storage root key does not exist, hence I try to create it with TPM_CreatePrimary using TPM_RH_OWNER as the primary handle. The swtpm responds: 
```code=389, description=TPM_RC_HIERARCHY - hierarchy is not enabled or is not correct for the use Handle number 1```

Ok, I  executed TPM_HierarchyControl authHandle=TPM_RH_OWNER and enable=TPM_RH_OWNER. It returned success, but the error remains.

Is the storage hierarchy enabled by default? or is it a BIOS which has to enable/disable it? Even after enabling it, I cannot create new key. Do you have any idea what I did wrong?

```TSS_Execute: Command 00000169 marshal
TSS_Execute_valist: Step 1: initialization
TSS_Execute_valist: Step 5: command encrypt
TSS_Sessions_GetDecryptSession: Found 0 decrypt sessions at 0
TSS_Execute_valist: Step 6 calculate HMACs
TSS_Execute_valist: Step 7 set command authorizations
TSS_Execute_valist: Step 8: process the command
TSS_AuthExecute: Executing TPM2_NV_ReadPublic
TSS_Dev_Open: Opening /dev/tpm0
TSS_Dev_SendCommand: TPM2_NV_ReadPublic
 TSS_Dev_SendCommand length 14
 80 01 00 00 00 0e 00 00 01 69 01 c0 00 02 
TSS_Dev_ReceiveCommand:
 TSS_Dev_ReceiveCommand length 62
 80 01 00 00 00 3e 00 00 00 00 00 0e 01 c0 00 02 
 00 0b 62 05 00 05 00 00 04 4c 00 22 00 0b 73 36 
 2d 7f 6a 18 de b5 aa 35 cf a4 f9 10 ef e3 c6 45 
 81 64 3a 1e be 45 20 db b3 93 66 c2 09 a5 
TSS_Dev_ReceiveCommand: rc 00000000
TSS_Execute_valist: Step 9 get response authorizations
TSS_Execute_valist: Step 13: response decryption
TSS_Sessions_GetEncryptSession: Found 0 encrypt sessions at 0
TSS_Execute: Command 00000169 unmarshal
TSS_Execute: Command 00000169 post processor
TSS_PO_NV_ReadPublic
TSS_Name_Store: Handle 01c00002
TSS_Execute: Command 0000017a marshal
TSS_Execute_valist: Step 1: initialization
TSS_Execute_valist: Step 5: command encrypt
TSS_Sessions_GetDecryptSession: Found 0 decrypt sessions at 0
TSS_Execute_valist: Step 6 calculate HMACs
TSS_Execute_valist: Step 7 set command authorizations
TSS_Execute_valist: Step 8: process the command
TSS_AuthExecute: Executing TPM2_GetCapability
TSS_Dev_SendCommand: TPM2_GetCapability
 TSS_Dev_SendCommand length 22
 80 01 00 00 00 16 00 00 01 7a 00 00 00 06 00 00 
 01 2c 00 00 00 01 
TSS_Dev_ReceiveCommand:
 TSS_Dev_ReceiveCommand length 27
 80 01 00 00 00 1b 00 00 00 00 01 00 00 00 06 00 
 00 00 01 00 00 01 2c 00 00 04 00 
TSS_Dev_ReceiveCommand: rc 00000000
TSS_Execute_valist: Step 9 get response authorizations
TSS_Execute_valist: Step 13: response decryption
TSS_Sessions_GetEncryptSession: Found 0 encrypt sessions at 0
TSS_Execute: Command 0000017a unmarshal
TSS_Execute: Command 0000017a post processor
TRACE:tpm20tss::info: Read max NV buffer: 1024
TSS_Execute: Command 0000014e marshal
TSS_Execute_valist: Step 1: initialization
TSS_Execute_valist: Step 2: authorization 0
TSS_Execute_valist: session 0 handle 40000009
TSS_Execute_valist: Step 5: command encrypt
TSS_Sessions_GetDecryptSession: Found 0 decrypt sessions at 0
TSS_Execute_valist: Step 6 calculate HMACs
TSS_HmacSession_SetHMAC: Step 6 session 40000009
TSS_Execute_valist: Step 7 set command authorizations
TSS_Execute_valist: Step 8: process the command
TSS_AuthExecute: Executing TPM2_NV_Read
TSS_Dev_SendCommand: TPM2_NV_Read
 TSS_Dev_SendCommand length 35
 80 02 00 00 00 23 00 00 01 4e 01 c0 00 02 01 c0 
 00 02 00 00 00 09 40 00 00 09 00 00 00 00 00 04 
 00 00 00 
TSS_Dev_ReceiveCommand:
 TSS_Dev_ReceiveCommand length 1045
 80 02 00 00 04 15 00 00 00 00 00 00 04 02 04 00 
 30 82 03 85 30 82 02 6d a0 03 02 01 02 02 02 03 
 e8 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 
 30 3a 31 0b 30 09 06 03 55 04 06 13 02 44 45 31 
 0f 30 0d 06 03 55 04 08 0c 06 53 61 78 6f 6e 79 
 31 0c 30 0a 06 03 55 04 0a 0c 03 54 55 44 31 0c 
 30 0a 06 03 55 04 03 0c 03 4c 41 53 30 1e 17 0d 
 31 39 30 33 32 32 31 30 35 30 32 37 5a 17 0d 32 
 30 30 33 32 31 31 30 35 30 32 37 5a 30 39 31 0b 
 30 09 06 03 55 04 06 13 02 49 54 31 0c 30 0a 06 
 03 55 04 08 0c 03 54 42 45 31 0d 30 0b 06 03 55 
 04 0a 0c 04 78 54 50 4d 31 0d 30 0b 06 03 55 04 
 03 0c 04 78 54 50 4d 30 82 01 22 30 0d 06 09 2a 
 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 
 82 01 0a 02 82 01 01 00 b4 7e 85 14 00 00 cc 26 
 28 69 01 30 83 cf 43 66 40 8d 23 b7 47 1b ca ff 
 dd 91 d0 43 47 d6 49 ab 0b 32 b0 25 65 8e b9 87 
 d5 87 8c 64 1c 85 4e 72 81 a2 09 82 56 9c d6 77 
 da 87 61 38 6f 32 bc ac e0 ee bf b1 7e 67 45 6f 
 aa 87 75 8f dc 25 4d 7c 3f ee 70 8a 55 9c 8b 9c 
 07 de f0 d8 5f a4 89 f0 db fb 74 88 92 04 66 e6 
 8f 77 b4 53 cd 90 c0 e3 62 fd 4f 38 56 db 02 a3 
 78 7d d1 90 47 03 82 61 a9 9f 80 63 a4 0b e7 00 
 17 e9 25 12 83 c2 57 d6 ea 6e c8 84 05 aa ed c7 
 3d 4b 27 2f 11 5b fc 3d 70 12 68 90 31 a1 f8 36 
 3e 94 13 32 ed 71 64 35 0d e8 67 21 50 7c 74 aa 
 7e 10 a2 ad 13 ca 65 41 1f 2a 18 bd 53 a0 ad 94 
 34 a9 2c e4 61 7d d7 5b 1a b3 79 ce 60 6e 83 e5 
 ec 2b e0 a1 cd 43 86 b5 cb 69 7d c3 c2 d1 1a af 
 74 69 df 29 70 2f 43 30 84 de c8 42 bf dc ce 87 
 4c 3f 2f 5c fa f1 26 95 02 03 01 00 01 a3 81 95 
 30 81 92 30 09 06 03 55 1d 13 04 02 30 00 30 0b 
 06 03 55 1d 0f 04 04 03 02 05 a0 30 22 06 03 55 
 1d 25 04 1b 30 19 06 08 2b 06 01 05 05 07 03 01 
 06 08 2b 06 01 05 05 07 03 02 06 03 88 37 01 30 
 1d 06 03 55 1d 0e 04 16 04 14 da 39 a3 ee 5e 6b 
 4b 0d 32 55 bf ef 95 60 18 90 af d8 07 09 30 1f 
 06 03 55 1d 23 04 18 30 16 80 14 da 39 a3 ee 5e 
 6b 4b 0d 32 55 bf ef 95 60 18 90 af d8 07 09 30 
 14 06 03 55 1d 11 04 0d 30 0b 82 09 6c 6f 63 61 
 6c 68 6f 73 74 30 0d 06 09 2a 86 48 86 f7 0d 01 
 01 0b 05 00 03 82 01 01 00 5f 57 86 b2 cb 86 53 
 c3 6d 09 14 ee 06 eb 2b 3f ac 9d c8 d1 27 2a 60 
 93 81 f4 de f4 05 7f 2d 78 d7 04 06 66 6e a4 4c 
 67 ae 60 f8 17 d6 a3 a8 36 c1 7b 27 ab e5 27 bd 
 0a ed 59 20 94 e8 c9 c1 06 dd 8e 58 ee e0 b4 70 
 95 1b a4 50 16 46 55 3c b2 80 a0 4f 87 9b 98 4c 
 44 c5 12 ca 95 90 bc bd dd be 90 d0 c6 ed 6f b3 
 b3 6c 25 04 62 ae ad e6 03 83 d2 0c f7 68 22 a6 
 48 6b e7 cd 8e 39 54 73 23 c5 6e 18 70 d0 36 79 
 4e bf 52 55 ae 21 86 a4 f8 e7 e1 06 6a 46 ef 3b 
 35 19 66 28 fe 0f b4 0d 07 cc de 7f 17 51 b9 d8 
 03 a8 49 22 da d8 8c 2d e4 8c 84 c3 72 e2 2e 8c 
 09 24 9c 36 cb 8d 34 2e 18 17 06 bc 06 77 79 5b 
 25 e6 83 a1 49 49 d2 fc 43 30 54 9f 83 d3 c5 e0 
 18 a1 71 cc d3 50 47 28 e4 74 7a 3f c8 6d cd 5b 
 91 df 0e d3 31 68 58 91 a7 44 8a 3e 2f da 6e 29 
 13 90 d8 4f dc db b1 f2 9a ff ff ff ff ff ff ff 
 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
 00 00 01 00 00 
TSS_Dev_ReceiveCommand: rc 00000000
TSS_Execute_valist: Step 9 get response authorizations
TSS_Execute_valist: Step 10: process response authorization 40000009
TSS_Execute_valist: Step 13: response decryption
TSS_Sessions_GetEncryptSession: Found 0 encrypt sessions at 0
TSS_Execute: Command 0000014e unmarshal
TSS_Execute: Command 0000014e post processor
TSS_Execute: Command 0000014e marshal
TSS_Execute_valist: Step 1: initialization
TSS_Execute_valist: Step 2: authorization 0
TSS_Execute_valist: session 0 handle 40000009
TSS_Execute_valist: Step 5: command encrypt
TSS_Sessions_GetDecryptSession: Found 0 decrypt sessions at 0
TSS_Execute_valist: Step 6 calculate HMACs
TSS_HmacSession_SetHMAC: Step 6 session 40000009
TSS_Execute_valist: Step 7 set command authorizations
TSS_Execute_valist: Step 8: process the command
TSS_AuthExecute: Executing TPM2_NV_Read
TSS_Dev_SendCommand: TPM2_NV_Read
 TSS_Dev_SendCommand length 35
 80 02 00 00 00 23 00 00 01 4e 01 c0 00 02 01 c0 
 00 02 00 00 00 09 40 00 00 09 00 00 00 00 00 00 
 4c 04 00 
TSS_Dev_ReceiveCommand:
 TSS_Dev_ReceiveCommand length 97
 80 02 00 00 00 61 00 00 00 00 00 00 00 4e 00 4c 
 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
 ff ff ff ff ff ff ff ff ff ff ff ff 00 00 01 00 
 00 
TSS_Dev_ReceiveCommand: rc 00000000
TSS_Execute_valist: Step 9 get response authorizations
TSS_Execute_valist: Step 10: process response authorization 40000009
TSS_Execute_valist: Step 13: response decryption
TSS_Sessions_GetEncryptSession: Found 0 encrypt sessions at 0
TSS_Execute: Command 0000014e unmarshal
TSS_Execute: Command 0000014e post processor
TSS_Execute: Command 0000017a marshal
TSS_Execute_valist: Step 1: initialization
TSS_Execute_valist: Step 5: command encrypt
TSS_Sessions_GetDecryptSession: Found 0 decrypt sessions at 0
TSS_Execute_valist: Step 6 calculate HMACs
TSS_Execute_valist: Step 7 set command authorizations
TSS_Execute_valist: Step 8: process the command
TSS_AuthExecute: Executing TPM2_GetCapability
TSS_Dev_SendCommand: TPM2_GetCapability
 TSS_Dev_SendCommand length 22
 80 01 00 00 00 16 00 00 01 7a 00 00 00 01 81 00 
 00 00 00 00 00 01 
TSS_Dev_ReceiveCommand:
 TSS_Dev_ReceiveCommand length 19
 80 01 00 00 00 13 00 00 00 00 00 00 00 00 01 00 
 00 00 00 
TSS_Dev_ReceiveCommand: rc 00000000
TSS_Execute_valist: Step 9 get response authorizations
TSS_Execute_valist: Step 13: response decryption
TSS_Sessions_GetEncryptSession: Found 0 encrypt sessions at 0
TSS_Execute: Command 0000017a unmarshal
TSS_Execute: Command 0000017a post processor
DEBUG:tpm20tss::attestation: Storage Root Key does not exist. Creating new one
TSS_Execute: Command 0000017a marshal
TSS_Execute_valist: Step 1: initialization
TSS_Execute_valist: Step 5: command encrypt
TSS_Sessions_GetDecryptSession: Found 0 decrypt sessions at 0
TSS_Execute_valist: Step 6 calculate HMACs
TSS_Execute_valist: Step 7 set command authorizations
TSS_Execute_valist: Step 8: process the command
TSS_AuthExecute: Executing TPM2_GetCapability
TSS_Dev_SendCommand: TPM2_GetCapability
 TSS_Dev_SendCommand length 22
 80 01 00 00 00 16 00 00 01 7a 00 00 00 01 81 00 
 00 00 00 00 00 01 
TSS_Dev_ReceiveCommand:
 TSS_Dev_ReceiveCommand length 19
 80 01 00 00 00 13 00 00 00 00 00 00 00 00 01 00 
 00 00 00 
TSS_Dev_ReceiveCommand: rc 00000000
TSS_Execute_valist: Step 9 get response authorizations
TSS_Execute_valist: Step 13: response decryption
TSS_Sessions_GetEncryptSession: Found 0 encrypt sessions at 0
TSS_Execute: Command 0000017a unmarshal
TSS_Execute: Command 0000017a post processor
TSS_Execute: Command 00000131 marshal
TSS_Execute_valist: Step 1: initialization
TSS_Execute_valist: Step 2: authorization 0
TSS_Execute_valist: session 0 handle 40000009
TSS_Execute_valist: Step 5: command encrypt
TSS_Sessions_GetDecryptSession: Found 0 decrypt sessions at 0
TSS_Execute_valist: Step 6 calculate HMACs
TSS_HmacSession_SetHMAC: Step 6 session 40000009
TSS_Execute_valist: Step 7 set command authorizations
TSS_Execute_valist: Step 8: process the command
TSS_AuthExecute: Executing TPM2_CreatePrimary
TSS_Dev_SendCommand: TPM2_CreatePrimary
 TSS_Dev_SendCommand length 67
 80 02 00 00 00 43 00 00 01 31 40 00 00 01 00 00 
 00 09 40 00 00 09 00 00 00 00 00 00 04 00 00 00 
 00 00 1a 00 01 00 0b 00 03 04 72 00 00 00 06 00 
 80 00 43 00 10 08 00 00 00 00 00 00 00 00 00 00 
 00 00 00 
TSS_Dev_ReceiveCommand:
 TSS_Dev_ReceiveCommand length 10
 80 01 00 00 00 0a 00 00 01 85 
TSS_Dev_ReceiveCommand: rc 00000185
TSS_Dev_Close: Closing /dev/tpm0```

**Comment by stefanberger** [comment] 2019-03-22 13:21
I cannot reproduce the problem you are seeing. I am using the TSS2 tools (built from sources; yours may have 'tss' prefix) and successfully ran the following commands:
```
[root@localhost utils]# ./createprimary -hi e
Handle 80000000
[root@localhost utils]# ./createprimary -hi o
Handle 80000001
[root@localhost utils]# ./createprimary -hi n
Handle 80000002
[root@localhost utils]# ./flushcontext -ha 80000000
[root@localhost utils]# ./flushcontext -ha 80000001
[root@localhost utils]# ./flushcontext -ha 80000002
```

Can you try to do the same and see what happens in your case? I had started out with a clean TPM 2.

**Comment by stefanberger** [comment] 2019-03-22 13:52
2 more suggestions if the above fails:
- next time you provision certs, shut down swtpm after provisioning and restart it before starting QEMU with it
- OR reboot the VM

**Comment by kgoldman** [comment] 2019-03-22 14:05
A few comments:
1. I captured your createprimary command byte stream and it ran for me, so I think it's OK.  Like you, I  suspect that the storage hierarchy is disabled.
2. When I use hierarchycontrol to disable the storage hierarchy, I also get the 185 response code.
3. The storage hierarchy should be enabled at startup.  AFAIK, it has to be explicitly disabled.
4. I wonder about your hierarchy control command.  Was the 'state' parameter true?  Could you have disabled it instead of enabling it?
5 .  getcapability -cap 6 -pr 201 -pc 1 can be used to read the state of the hierarchy enables.

**Comment by wojciechozga** [comment] 2019-03-22 14:31
Since the [https://github.com/stefanberger/swtpm](url)) is not enough for my use case, I have my own implementation of the SGX-based virtual TPM. I run `libtpms` directly (not via swtpm) which caused the aforementioned behaviour.

The mentioned problem is related to my implementation: the first thing which I do is TPM manufacturing; I start the libtpms (`TPMLIB_MainInit`), tpm startup, change eps, create primary, issue certificate, NV define, NV write, NV lock, tpm shutdown. At this point, I was *not* closing libtpms (`TPMLIB_Terminate`) but starting QEMU. At the end of the process, I had the certificate inside NV but I could not create new keys. 

After running `TPMLIB_Terminate` after manufacturing, I can create new keys under all hierarchies but the certificate is gone. I guess, on `TPMLIB_Terminate`, the state is gone, including the NV content (I do not use the mechanism from swtpm of storing state inside the file).

I believe that keeping the state persisted across tpmlib terminate/maininit and running TPMLIB_Terminate after manufacturing should solve my problem.

Thanks for help!

**Comment by stefanberger** [comment] 2019-03-22 14:36
You have to persist the state otherwise it's gone. If your problem is solved, can you please close the issue. 

Also, ideally there would be a way to compile `swtpm` for sgx support as well...

**Closed** 2019-03-22 14:36 UTC

**Comment by wojciechozga** [comment] 2019-03-22 14:38
Yes, some weeks ago I also managed to cross-compile swtpm with SCONE, it worked fine.

**Comment by wojciechozga** [comment] 2019-03-22 19:31
I am not sure if I understand correctly how the get/set of the state works in libtpms. What I did is:
- Before `TPMLIB_Terminate()` I run `TPMLIB_GetState` to get the permanent and volatile state (permanent contains the previously written EK certificate)
- Before `TPMLIB_MainInit()` I run `TPMLIB_SetState` to write back both states previously obtained from `TPMLIB_GetState`

I receive TPM_RC_NV_UNAVAILABLE: "the command may require writing of NV and NV is not current accessible".

**Comment by stefanberger** [comment] 2019-03-22 20:14
Try to set the state *after* TPMLIB_MainInit().

**Comment by wojciechozga** [comment] 2019-03-22 21:12
When I run it after TPMLIB_MainInit() I get TPM_INVALID_POSTINIT due to this condition:
```
/ * Set the state the TPM 2 will use upon next TPM_MainInit(). The TPM 2
 * must not have been started, yet, or it must have been terminated for this
 * function to set the state. */
TPM_RESULT TPM2_SetState(enum TPMLIB_StateType st,
                         const unsigned char *buffer, uint32_t buflen)
{
...
if (_rpc__Signal_IsPowerOn())
        return TPM_INVALID_POSTINIT;
...
}
```

**Comment by stefanberger** [comment] 2019-03-22 23:32
The safest bet may be to call `TPM_RESULT TPMLIB_RegisterCallbacks(struct tpmlibrary_callbacks *);` and fill out that interface with functions. The `tpm_nvram_loaddata` and `tpm_nvram_storedata` can then be use to store the blobs in memory and retrieve them later on.

**Comment by stefanberger** [comment] 2019-03-23 02:12
I applied this modification to tests/tpm2_pcr_read.c:

```
diff --git a/tests/tpm2_pcr_read.c b/tests/tpm2_pcr_read.c
index 6028d7e..acf6a8c 100644
--- a/tests/tpm2_pcr_read.c
+++ b/tests/tpm2_pcr_read.c
@@ -123,6 +123,27 @@ int main(void)

     ret = 0;

+    unsigned char *perm;
+    uint32_t permlen = 0;
+    res = TPMLIB_GetState(TPMLIB_STATE_PERMANENT, &perm, &permlen);
+    printf("res= %d , permlen = %d\n", res, permlen);
+
+    unsigned char *vol;
+    uint32_t vollen = 0;
+    res = TPMLIB_GetState(TPMLIB_STATE_VOLATILE, &vol, &vollen);
+    printf("res= %d , vollen = %d\n", res, vollen);
+
+    TPMLIB_Terminate();
+    res = TPMLIB_SetState(TPMLIB_STATE_PERMANENT, perm, permlen);
+    printf("res=%d\n", res);
+    res = TPMLIB_SetState(TPMLIB_STATE_VOLATILE, vol, vollen);
+    printf("res=%d\n", res);
+    res = TPMLIB_MainInit();
+    if (res != TPM_SUCCESS) {
+        fprintf(stderr, "TPMLIB_MainInit() failed\n");
+        goto exit;
+    }
+
 exit:
     TPMLIB_Terminate();
     TPM_Free(rbuffer);
```

This is the output:
```
$ ./tpm2_pcr_read.exe
res= 0 , permlen = 1165
res= 0 , vollen = 8900
res=0
res=0
```

It works fine here. The permanent state must be set before the volatile state.

**Comment by wojciechozga** [comment] 2019-03-24 11:46
Hi,
I modified the tpm2_pcr_read.c to reflect this scenario ([https://pastebin.com/xeGF7VFT](url)):
```TPMLIB_ChooseTPMVersion(TPMLIB_TPM_VERSION_2)
TPMLIB_MainInit()
TPMLIB_Process(TPM2_Startup)
TPMLIB_Process(TPM2_Shutdown)
TPMLIB_GetState(PERMANENT + VOLATILE)
TPMLIB_Terminate();
TPMLIB_SetState(PERMANENT + VOLATILE)
TPMLIB_MainInit()
TPMLIB_Process(TPM2_Startup)
TPMLIB_Process(TPM2_Shutdown)
```

After loading the state the Startup command and Shutdown command fail:
```
Response Startup: 80 1 0 0 0 a 0 0 1 0, Error=1
Response Shutdown: 80 1 0 0 0 a 0 0 923, Error=1 
```
where the errors are:
for TPM2_Startup: TPM_RC_INITIALIZE
for TPM2_Shutdown: TPM_RC_NV_UNAVAILABLE

I have also tried scenarios where I do not execute TPM2_Shutdown at all but still TPM2_Startup fails. Again, TPM2_Startup does not return error when TPMLIB_SetState is not executed. Moreover, I can execute TPM2_PCR_Read successfully after loading the state even before running TPM2_Startup.

Is it the expected behaviour? Does it mean, that by loading the state the TPM is already started up? Why it cannot be later shutdown?

Thanks for the support!

**Comment by wojciechozga** [comment] 2019-03-24 15:02
@kgoldman thanks for your comment.

As you suggested, I run the getcapability:
```
ubuntu@ubuntu:~/utils$ sudo TPM_INTERFACE_TYPE=dev ./getcapability -cap 6 -pr 201 -pc 1
moreData: 1
1 properties
TPM_PT 00000201 value 80000009 TPM_PT_STARTUP_CLEAR - TPMA_STARTUP_CLEAR
```
In my hierarchy control command I set 'state' to true. 
```
ubuntu@ubuntu:~/utils$ sudo TPM_INTERFACE_TYPE=dev ./hierarchycontrol -hi p -he o -state 1
```

Now, the hierarchy is enabled:
```
ubuntu@ubuntu:~/utils$ sudo TPM_INTERFACE_TYPE=dev ./getcapability -cap 6 -pr 201 -pc 1
moreData: 1
1 properties
TPM_PT 00000201 value 8000000b TPM_PT_STARTUP_CLEAR - TPMA_STARTUP_CLEAR
```

After that, I create new key under the storage hierarchy (TPM_CC_CreatePrimary):
```
[80, 2, 0, 0, 0, 43, 0, 0, 1, 31, 40, 0, 0, 1, 0, 0, 0, 9, 40, 0, 0, 9, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 1a, 0, 1, 0, b, 0, 3, 4, 72, 0, 0, 0, 6, 0, 80, 0, 43, 0, 10, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```
and then, I make it persistent with TPM_CC_EvictControl:
```
request: [80, 2, 0, 0, 0, 23, 0, 0, 1, 20, 40, 0, 0, 1, 80, 0, 0, 0, 0, 0, 0, 9, 40, 0, 0, 9, 0, 0, 0, 0, 0, 81, 0, 0, 1]
```
which returns TPM_RC_NV_UNAVAILABLE "the command may require writing of NV and NV is not current accessible":
```
response: [80, 1, 0, 0, 0, a, 0, 0, 9, 23]
```

I think the state of the emulated TPM is corrupted after I try to recover it before the initialisation. I get the same behaviour (TPM_RC_NV_UNAVAILABLE) when I perform this simplified scenario:
```
TPMLIB_MainInit()
TPMLIB_Process(TPM2_Startup)
TPMLIB_Process(TPM2_Shutdown)
TPMLIB_GetState(PERMANENT + VOLATILE)
TPMLIB_Terminate();
TPMLIB_SetState(PERMANENT + VOLATILE)
TPMLIB_MainInit()
TPMLIB_Process(TPM2_Startup)
TPMLIB_Process(TPM2_Shutdown)
```

**Comment by stefanberger** [comment] 2019-03-24 22:29
> Is it the expected behaviour? Does it mean that after loading the state the TPM is already started up? Why it cannot be later shutdown?

Yes, this is expected behavior since you are resuming the vTPM where you left off. You could try to leave out the volatile state saving/restoring and try to run it with STARTUP then. This should work then.

**Comment by stefanberger** [comment] 2019-03-25 13:30
@wojciechozga If you cannot get it to work, please send me source code that I can try out myself and/or modify so we get it to work. It has to work without SGX, though. Ideally it would be a test case like this one here now: PR #35

**Comment by stefanberger** [comment] 2019-03-25 14:14
@wojciechozga Looks like there is a bug in the re-enablement of the NvRAM. This patch should fix it:

```
diff --git a/src/tpm_tpm2_interface.c b/src/tpm_tpm2_interface.c
index 4ea85373..61bc010b 100644
--- a/src/tpm_tpm2_interface.c
+++ b/src/tpm_tpm2_interface.c
@@ -120,8 +120,8 @@ TPM_RESULT TPM2_MainInit(void)
 
     has_cached_state = HasCachedState(TPMLIB_STATE_PERMANENT);
 
+    _plat__NVEnable(NULL);
     if (!has_cached_state && !_TPM2_CheckNVRAMFileExists()) {
-        _plat__NVEnable(NULL);
         if (TPM_Manufacture(TRUE) < 0 || g_inFailureMode) {
             TPMLIB_LogTPM2Error("%s: TPM_Manufacture(TRUE) failed or TPM in "
                                 "failure mode\n", __func__);
```

**Comment by stefanberger** [comment] 2019-03-25 15:10
@wojciechozga Can you please check that the fix in `master.next` addresses the problems you are seeing? Though you have to be careful in your code with restoring the volatile state since this resumes the vTPM where it was left off, so you may have to remove this part.

**Comment by wojciechozga** [comment] 2019-03-25 21:01
@stefanberger the patch resolved my problem. I tested my code with `master.next` and I can now successfully access NV registers after restoring the permanent state using TPMLIB_SetState().

As you suggested, I have also tried setting callbacks (using `master`) and it worked too. 

Thank you!

**Comment by stefanberger** [comment] 2019-03-26 14:25
@wojciechozga I merged the patches into master now.
